In [8]:
import numpy as np
import sys

## Basics

In [12]:
# How to add two arrays

a = np.array([1,2,3])
b = np.array([2,2,3])

c = a*b
print(c)

[2 4 9]


In [33]:
# 2D Array
b = np.array([[1,2,3,4], [4,5,6,6]])
print(b)

[[1 2 3 4]
 [4 5 6 6]]


In [25]:
# 3D Array
c = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [29]:
# Get Dimensions of an array
a.ndim

2

In [37]:
# Get Shape

c.shape

(1, 3, 3)

In [42]:
# Get Size
a.itemsize

8