In [8]:
import numpy as np
import sys

## Basics

In [12]:
# How to add two arrays

a = np.array([1,2,3])
b = np.array([2,2,3])

c = a*b
print(c)

[2 4 9]


In [33]:
# 2D Array
b = np.array([[1,2,3,4], [4,5,6,6]])
print(b)

[[1 2 3 4]
 [4 5 6 6]]


In [25]:
# 3D Array
c = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [29]:
# Get Dimensions of an array
a.ndim

2

In [37]:
# Get Shape

c.shape

(1, 3, 3)

In [49]:
# Get Size
a = np.array([1,2,3], dtype='int16')
a.itemsize

2

# Accessing/Changing specific elements, rows, columns, etc

In [51]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [53]:
# Get a specific item [r, c]
a[1,-3] = 99

In [55]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 99 13 14]]


In [59]:
# Get a specific row
a[1]

array([ 8,  9, 10, 11, 99, 13, 14])

In [64]:
# Get specific element from 3D array

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

# Get 6 from the array

print(b[1,0,1])

6


# Initializing Different Types of Arrays

6