In [8]:
import numpy as np
import sys

## Basics

In [12]:
# How to add two arrays

a = np.array([1,2,3])
b = np.array([2,2,3])

c = a*b
print(c)

[2 4 9]


In [33]:
# 2D Array
b = np.array([[1,2,3,4], [4,5,6,6]])
print(b)

[[1 2 3 4]
 [4 5 6 6]]


In [25]:
# 3D Array
c = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [29]:
# Get Dimensions of an array
a.ndim

2

In [37]:
# Get Shape

c.shape

(1, 3, 3)

In [49]:
# Get Size
a = np.array([1,2,3], dtype='int16')
a.itemsize

2

# Accessing/Changing specific elements, rows, columns, etc

In [51]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [53]:
# Get a specific item [r, c]
a[1,-3] = 99

In [55]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 99 13 14]]


In [59]:
# Get a specific row
a[1]

array([ 8,  9, 10, 11, 99, 13, 14])

In [64]:
# Get specific element from 3D array

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

# Get 6 from the array

print(b[1,0,1])

6


# Initializing Different Types of Arrays

In [68]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [71]:
# All 1s matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
# Any other number
np.full((2,2), 33)

array([[33, 33],
       [33, 33]])

In [75]:
# Random decimal number
np.random.rand(3, 2)

array([[0.27712286, 0.4335423 ],
       [0.70538995, 0.32869156],
       [0.68638381, 0.20671767]])

In [79]:
# Random integer values
np.random.randint(3,size=(3,3))

array([[2, 1, 0],
       [0, 0, 0],
       [2, 0, 2]])

In [81]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
# Any other number
x = np.full((5,5), 1)
x[1] = [1,0,0,0,1]
x[-2] = [1,0,0,0,1]
x[2,2] = 9
x



array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 9, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])